export default {
  // token request home
  ACTION_FETCH_TOKEN: 'ACTION_FETCH_TOKEN',

  ACTION_API_ERROR_SUCCESS: 'ACTION_API_ERROR_SUCCESS',
  ACTION_API_ERROR_REQUEST:'ACTION_API_ERROR_REQUEST',

  ACTION_GET_ACCESS_TOKEN_REQUEST: 'ACTION_GET_ACCESS_TOKEN_REQUEST',
  ACTION_GET_ACCESS_TOKEN_SUCCESS: 'ACTION_GET_ACCESS_TOKEN_SUCCESS',
  ACTION_GET_ACCESS_TOKEN_FAILURE: 'ACTION_GET_ACCESS_TOKEN_FAILURE',

  // user profile request

  ACTION_GET_USER_PROFILE_REQUEST: 'ACTION_GET_USER_PROFILE_REQUEST',
  ACTION_GET_USER_PROFILE_SUCCESS: 'ACTION_GET_USER_PROFILE_SUCCESS',
  ACTION_GET_USER_PROFILE_FAILURE: 'ACTION_GET_USER_PROFILE_FAILURE',

  // Itinary list request
  ACTION_GET_ITINARY_LIST_REQUEST: 'ACTION_GET_ITINARY_LIST_REQUEST',
  ACTION_GET_ITINARY_LIST_SUCCESS: 'ACTION_GET_ITINARY_LIST_SUCCESS',
  ACTION_GET_ITINARY_LIST_FAILURE: 'ACTION_GET_ITINARY_LIST_FAILURE',

  // Itinary list ALL JOURNEY request
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_REQUEST:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_REQUEST',
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_SUCCESS:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_SUCCESS',
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_FAILURE:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_FAILURE',

  // Approval  list request
  ACTION_GET_APPROVAL_LIST_REQUEST: 'ACTION_GET_APPROVAL_LIST_REQUEST',
  ACTION_GET_APPROVAL_LIST_SUCCESS: 'ACTION_GET_APPROVAL_LIST_SUCCESS',
  ACTION_GET_APPROVAL_LIST_FAILURE: 'ACTION_GET_APPROVAL_LIST_FAILURE',

  ACTION_GET_APPROVAL_LIST_WITH_STATUS_REQUEST: 'ACTION_GET_APPROVAL_LIST_WITH_STATUS_REQUEST',
  ACTION_GET_APPROVAL_LIST_WITH_STATUS_SUCCESS: 'ACTION_GET_APPROVAL_LIST_WITH_STATUS_SUCCESS',
  ACTION_GET_APPROVAL_LIST_WITH_STATUS_FAILURE: 'ACTION_GET_APPROVAL_LIST_WITH_STATUS_FAILURE',

  ACTION_GET_PENDING_APPROVAL_LIST_REQUEST: 'ACTION_GET_PENDING_APPROVAL_LIST_REQUEST',
  ACTION_GET_PENDING_APPROVAL_LIST_SUCCESS: 'ACTION_GET_PENDING_APPROVAL_LIST_SUCCESS',
  ACTION_GET_PENDING_APPROVAL_LIST_FAILURE: 'ACTION_GET_PENDING_APPROVAL_LIST_FAILURE',

  ACTION_GET_APPROVED_APPROVAL_LIST_REQUEST: 'ACTION_GET_APPROVED_APPROVAL_LIST_REQUEST',
  ACTION_GET_APPROVED_APPROVAL_LIST_SUCCESS: 'ACTION_GET_APPROVED_APPROVAL_LIST_SUCCESS',
  ACTION_GET_APPROVED_APPROVAL_LIST_FAILURE: 'ACTION_GET_APPROVED_APPROVAL_LIST_FAILURE',

  ACTION_ACCEPT_APPROVAL_REQUEST: 'ACTION_ACCEPT_APPROVAL_REQUEST',
  ACTION_ACCEPT_APPROVAL_SUCCESS: 'ACTION_ACCEPT_APPROVAL_SUCCESS',
  ACTION_ACCEPT_APPROVAL_FAILURE: 'ACTION_ACCEPT_APPROVAL_FAILURE',

  ACTION_DECLINE_APPROVAL_REQUEST: 'ACTION_DECLINE_APPROVAL_REQUEST',
  ACTION_DECLINE_APPROVAL_SUCCESS: 'ACTION_DECLINE_APPROVAL_SUCCESS',
  ACTION_DECLINE_APPROVAL_FAILURE: 'ACTION_DECLINE_APPROVAL_FAILURE',

  ACTION_APPROVAL_DETAIL_REQUEST: 'ACTION_APPROVAL_DETAIL_REQUEST',
  ACTION_APPROVAL_DETAIL_SUCCESS: 'ACTION_APPROVAL_DETAIL_SUCCESS',
  ACTION_APPROVAL_DETAIL_FAILURE: 'ACTION_APPROVAL_DETAIL_FAILURE',

  // Upcoming Journeys

  ACTION_GET_UPCOMING_JOURNEY_REQUEST: 'ACTION_GET_UPCOMING_JOURNEY_REQUEST',
  ACTION_GET_UPCOMING_JOURNEY_SUCCESS: 'ACTION_GET_UPCOMING_JOURNEY_SUCCESS',
  ACTION_GET_UPCOMING_JOURNEY_FAILURE: 'ACTION_GET_UPCOMING_JOURNEY_FAILURE',

  // SITE TRAVEL ITINARY Detail

  ACTION_GET_DETAIL_OF_ITINARY_REQUEST: 'ACTION_GET_DETAIL_OF_ITINARY_REQUEST',
  ACTION_GET_DETAIL_OF_ITINARY_SUCCESS: 'ACTION_GET_DETAIL_OF_ITINARY_SUCCESS',
  ACTION_GET_DETAIL_OF_ITINARY_FAILURE: 'ACTION_GET_DETAIL_OF_ITINARY_FAILURE',
  
  // SITE TRAVEL ITINARY CANCEL

  ACTION_SITE_TRAVEL_ITINARY_CANCEL_REQUEST: 'ACTION_SITE_TRAVEL_ITINARY_CANCEL_REQUEST',
  ACTION_SITE_TRAVEL_ITINARY_CANCEL_SUCCESS: 'ACTION_SITE_TRAVEL_ITINARY_CANCEL_SUCCESS',
  ACTION_SITE_TRAVEL_ITINARY_CANCEL_FAILURE: 'ACTION_SITE_TRAVEL_ITINARY_CANCEL_FAILURE',

  // Booking summary 

  ACTION_BOOKING_SUMMARY_REQUEST: 'ACTION_BOOKING_SUMMARY_REQUEST',
  ACTION_BOOKING_SUMMARY_SUCCESS: 'ACTION_BOOKING_SUMMARY_SUCCESS',
  ACTION_BOOKING_SUMMARY_FAILURE: 'ACTION_BOOKING_SUMMARY_FAILURE',

  //POST BUS BOOKING

  ACTION_POST_BUS_BOOKING_REQUEST: 'ACTION_POST_BUS_BOOKING_REQUEST',
  ACTION_POST_BUS_BOOKING_SUCCESS: 'ACTION_POST_BUS_BOOKING_SUCCESS',
  ACTION_POST_BUS_BOOKING_FAILURE: 'ACTION_POST_BUS_BOOKING_FAILURE',

  // CANCEL BUS BOOKING

  ACTION_CANCEL_BUS_BOOKING_REQUEST: 'ACTION_CANCEL_BUS_BOOKING_REQUEST',
  ACTION_CANCEL_BUS_BOOKING_SUCCESS: 'ACTION_CANCEL_BUS_BOOKING_SUCCESS',
  ACTION_CANCEL_BUS_BOOKING_FAILURE: 'ACTION_CANCEL_BUS_BOOKING_FAILURE',

  // GET BUS ROUTE BASED ON PICKUP DROPOFF

  ACTION_GET_BUS_ROUTE_REQUEST: 'ACTION_GET_BUS_ROUTE_REQUEST',
  ACTION_GET_BUS_ROUTE_SUCCESS: 'ACTION_GET_BUS_ROUTE_SUCCESS',
  ACTION_GET_BUS_ROUTE_FAILURE: 'ACTION_GET_BUS_ROUTE_FAILURE',

  // GET BUS STOPS
  ACTION_GET_BUS_STOP_REQUEST: 'ACTION_GET_BUS_STOP_REQUEST',
  ACTION_GET_BUS_STOP_SUCCESS: 'ACTION_GET_BUS_STOP_SUCCESS',
  ACTION_GET_BUS_STOP_FAILURE: 'ACTION_GET_BUS_STOP_FAILURE',

  // GET ITINARY DETAILS

  ACTION_GET_ITINARY_DETAILS_REQUEST: 'ACTION_GET_ITINARY_DETAILS_REQUEST',
  ACTION_GET_ITINARY_DETAILS_SUCCESS: 'ACTION_GET_ITINARY_DETAILS_SUCCESS',
  ACTION_GET_ITINARY_DETAILS_FAILURE: 'ACTION_GET_ITINARY_DETAILS_FAILURE',

  //** AUTHORISATION FLOW */
  // GET API BASE 

  ACTION_SET_LOGIN_LOADER: 'ACTION_SET_LOGIN_LOADER',

  ACTION_GET_API_BASE_REQUEST: 'ACTION_GET_API_BASE_REQUEST',
  ACTION_GET_API_BASE_SUCCESS: 'ACTION_GET_API_BASE_SUCCESS',
  ACTION_GET_API_BASE_FAILURE: 'ACTION_GET_API_BASE_FAILURE',

  ACTION_GET_CLIENT_TOKEN_REQUEST: 'ACTION_GET_CLIENT_TOKEN_REQUEST',
  ACTION_GET_CLIENT_TOKEN_SUCCESS: 'ACTION_GET_CLIENT_TOKEN_SUCCESS',
  ACTION_GET_CLIENT_TOKEN_FAILURE: 'ACTION_GET_CLIENT_TOKEN_FAILURE',

  ACTION_GET_ACCOUNT_URL_REQUEST: 'ACTION_GET_ACCOUNT_URL_REQUEST',
  ACTION_GET_ACCOUNT_URL_SUCCESS: 'ACTION_GET_ACCOUNT_URL_SUCCESS',
  ACTION_GET_ACCOUNT_URL_FAILURE: 'ACTION_GET_ACCOUNT_URL_FAILURE',

// Action Get reason for decline 

  ACTION_GET_DECLINE_REASON_REQUEST: 'ACTION_GET_DECLINE_REASON_REQUEST',
  ACTION_GET_DECLINE_REASON_SUCCESS: 'ACTION_GET_DECLINE_REASON_SUCCESS',
  ACTION_GET_DECLINE_REASON_FAILURE: 'ACTION_GET_DECLINE_REASON_FAILURE',

  ACTION_SUBMIT_DECLINE_REASON_REQUEST: 'ACTION_SUBMIT_DECLINE_REASON_REQUEST',
  ACTION_SUBMIT_DECLINE_REASON_SUCCESS: 'ACTION_SUBMIT_DECLINE_REASON_SUCCESS',
  ACTION_SUBMIT_DECLINE_REASON_FAILURE: 'ACTION_SUBMIT_DECLINE_REASON_FAILURE',

  // Get Journeys list 

  ACTION_GET_JOURNEYS_LIST_REQUEST: 'ACTION_GET_JOURNEYS_LIST_REQUEST',
  ACTION_GET_JOURNEYS_LIST_SUCCESS: 'ACTION_GET_JOURNEYS_LIST_SUCCESS',
  ACTION_GET_JOURNEYS_LIST_FAILURE: 'ACTION_GET_JOURNEYS_LIST_FAILURE',


};
