export default{
    // token request home 
    ACTION_GET_ACCESS_TOKEN_REQUEST: 'ACTION_GET_ACCESS_TOKEN_REQUEST',
    ACTION_GET_ACCESS_TOKEN_SUCCESS: 'ACTION_GET_ACCESS_TOKEN_SUCCESS',
    ACTION_GET_ACCESS_TOKEN_FAILURE: 'ACTION_GET_ACCESS_TOKEN_FAILURE',

    // user profile request

    ACTION_GET_USER_PROFILE_REQUEST: 'ACTION_GET_USER_PROFILE_REQUEST',
    ACTION_GET_USER_PROFILE_SUCCESS: 'ACTION_GET_USER_PROFILE_SUCCESS',
    ACTION_GET_USER_PROFILE_FAILURE: 'ACTION_GET_USER_PROFILE_FAILURE',

    // Itinary list request

    ACTION_GET_ITINARY_LIST_REQUEST: 'ACTION_GET_ITINARY_LIST_REQUEST',
    ACTION_GET_ITINARY_LIST_SUCCESS: 'ACTION_GET_ITINARY_LIST_SUCCESS',
    ACTION_GET_ITINARY_LIST_FAILURE: 'ACTION_GET_ITINARY_LIST_FAILURE',

}