export default {
  // token request home
  ACTION_FETCH_TOKEN: 'ACTION_FETCH_TOKEN',
  ACTION_GET_ACCESS_TOKEN_REQUEST: 'ACTION_GET_ACCESS_TOKEN_REQUEST',
  ACTION_GET_ACCESS_TOKEN_SUCCESS: 'ACTION_GET_ACCESS_TOKEN_SUCCESS',
  ACTION_GET_ACCESS_TOKEN_FAILURE: 'ACTION_GET_ACCESS_TOKEN_FAILURE',

  // user profile request

  ACTION_GET_USER_PROFILE_REQUEST: 'ACTION_GET_USER_PROFILE_REQUEST',
  ACTION_GET_USER_PROFILE_SUCCESS: 'ACTION_GET_USER_PROFILE_SUCCESS',
  ACTION_GET_USER_PROFILE_FAILURE: 'ACTION_GET_USER_PROFILE_FAILURE',

  // Itinary list request
  ACTION_GET_ITINARY_LIST_REQUEST: 'ACTION_GET_ITINARY_LIST_REQUEST',
  ACTION_GET_ITINARY_LIST_SUCCESS: 'ACTION_GET_ITINARY_LIST_SUCCESS',
  ACTION_GET_ITINARY_LIST_FAILURE: 'ACTION_GET_ITINARY_LIST_FAILURE',

  // Itinary list ALL JOURNEY request
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_REQUEST:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_REQUEST',
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_SUCCESS:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_SUCCESS',
  ACTION_GET_ITINARY_LIST_ALL_JOURNEY_FAILURE:
    'ACTION_GET_ITINARY_LIST_ALL_JOURNEY_FAILURE',

  // Itinary list request
  ACTION_GET_APPROVAL_LIST_REQUEST: 'ACTION_GET_APPROVAL_LIST_REQUEST',
  ACTION_GET_APPROVAL_LIST_SUCCESS: 'ACTION_GET_APPROVAL_LIST_SUCCESS',
  ACTION_GET_APPROVAL_LIST_FAILURE: 'ACTION_GET_APPROVAL_LIST_FAILURE',

  // Upcoming Journeys

  ACTION_GET_UPCOMING_JOURNEY_REQUEST: 'ACTION_GET_UPCOMING_JOURNEY_REQUEST',
  ACTION_GET_UPCOMING_JOURNEY_SUCCESS: 'ACTION_GET_UPCOMING_JOURNEY_SUCCESS',
  ACTION_GET_UPCOMING_JOURNEY_FAILURE: 'ACTION_GET_UPCOMING_JOURNEY_FAILURE',

  // SITE TRAVEL ITINARY

  ACTION_SITE_TRAVEL_ITINARY_REQUEST: 'ACTION_SITE_TRAVEL_ITINARY_REQUEST',
  ACTION_SITE_TRAVEL_ITINARY_SUCCESS: 'ACTION_SITE_TRAVEL_ITINARY_SUCCESS',
  ACTION_SITE_TRAVEL_ITINARY_FAILURE: 'ACTION_SITE_TRAVEL_ITINARY_FAILURE',

  // SITE TRAVEL ITINARY

  ACTION_SITE_TRAVEL_ITINARY_REQUEST: 'ACTION_SITE_TRAVEL_ITINARY_REQUEST',
  ACTION_SITE_TRAVEL_ITINARY_SUCCESS: 'ACTION_SITE_TRAVEL_ITINARY_SUCCESS',
  ACTION_SITE_TRAVEL_ITINARY_FAILURE: 'ACTION_SITE_TRAVEL_ITINARY_FAILURE',

  // SITE TRAVEL ITINARY

  ACTION_BOOKING_SUMMARY_REQUEST: 'ACTION_BOOKING_SUMMARY_REQUEST',
  ACTION_BOOKING_SUMMARY_SUCCESS: 'ACTION_BOOKING_SUMMARY_SUCCESS',
  ACTION_BOOKING_SUMMARY_FAILURE: 'ACTION_BOOKING_SUMMARY_FAILURE',

  //POST BUS BOOKING

  ACTION_POST_BUS_BOOKING_REQUEST: 'ACTION_POST_BUS_BOOKING_REQUEST',
  ACTION_POST_BUS_BOOKING_SUCCESS: 'ACTION_POST_BUS_BOOKING_SUCCESS',
  ACTION_POST_BUS_BOOKING_FAILURE: 'ACTION_POST_BUS_BOOKING_FAILURE',

  // CANCEL BUS BOOKING

  ACTION_CANCEL_BUS_BOOKING_REQUEST: 'ACTION_CANCEL_BUS_BOOKING_REQUEST',
  ACTION_CANCEL_BUS_BOOKING_SUCCESS: 'ACTION_CANCEL_BUS_BOOKING_SUCCESS',
  ACTION_CANCEL_BUS_BOOKING_FAILURE: 'ACTION_CANCEL_BUS_BOOKING_FAILURE',

  // GET BUS ROUTE BASED ON PICKUP DROPOFF

  ACTION_GET_BUS_ROUTE_REQUEST: 'ACTION_GET_BUS_ROUTE_REQUEST',
  ACTION_GET_BUS_ROUTE_SUCCESS: 'ACTION_GET_BUS_ROUTE_SUCCESS',
  ACTION_GET_BUS_ROUTE_FAILURE: 'ACTION_GET_BUS_ROUTE_FAILURE',

  // GET BUS STOPS
  ACTION_GET_BUS_STOP_REQUEST: 'ACTION_GET_BUS_STOP_REQUEST',
  ACTION_GET_BUS_STOP_SUCCESS: 'ACTION_GET_BUS_STOP_SUCCESS',
  ACTION_GET_BUS_STOP_FAILURE: 'ACTION_GET_BUS_STOP_FAILURE',

  // GET ITINARY DETAILS

  ACTION_GET_ITINARY_DETAILS_REQUEST: 'ACTION_GET_ITINARY_DETAILS_REQUEST',
  ACTION_GET_ITINARY_DETAILS_SUCCESS: 'ACTION_GET_ITINARY_DETAILS_SUCCESS',
  ACTION_GET_ITINARY_DETAILS_FAILURE: 'ACTION_GET_ITINARY_DETAILS_FAILURE',
};
