export default{
    BARLOW_BOLD:'Barlow-Bold',
    BARLOW_REGULAR:'Barlow-Regular',
    BARLOW_SEMI_BOLD:'Barlow-SemiBold',

    TEXT_H1_SIZE_BOLD:35,
    TEXT_H2_SIZE_BOLD:22,
    TEXT_H3_SIZE_BOLD:17,
    TEXT_14_SIZE_BOLD:14,
    TEXT_12_SIZE_BOLD:12,



    TEXT_H1_SIZE_REGULAR:14,
    TEXT_H2_SIZE_REGULAR:12,
    TEXT_H3_SIZE_REGULAR:9,

    
}